### PR TITLE
Implement fallback for old MacOS versions

### LINKED ISSUE #1686: 3.4.1 build error on macOS: `DarwinProcess.c: error: ‘thread_extended_info_data_t’ undeclared`
```
    /usr/bin/gcc-4.2 -std=gnu99 -DHAVE_CONFIG_H -I.  -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -std=c99 -pedantic -D_DARWIN_C_SOURCE -DNCURSES_WIDECHAR -Wall -Wcast-align -Wcast-qual -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Wmissing-format-attribute -Wmissing-noreturn -Wmissing-prototypes -Wpointer-arith -Wshadow -Wstrict-prototypes -Wundef -Wunused -Wwrite-strings -DSYSCONFDIR="\"/opt/local/etc\"" -I"./darwin" -pipe -Os -arch ppc -MT zfs/ZfsArcMeter.o -MD -MP -MF $depbase.Tpo -c -o zfs/ZfsArcMeter.o zfs/ZfsArcMeter.c &&\
    mv -f $depbase.Tpo $depbase.Po
depbase=`echo zfs/ZfsCompressedArcMeter.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    /usr/bin/gcc-4.2 -std=gnu99 -DHAVE_CONFIG_H -I.  -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -std=c99 -pedantic -D_DARWIN_C_SOURCE -DNCURSES_WIDECHAR -Wall -Wcast-align -Wcast-qual -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Wmissing-format-attribute -Wmissing-noreturn -Wmissing-prototypes -Wpointer-arith -Wshadow -Wstrict-prototypes -Wundef -Wunused -Wwrite-strings -DSYSCONFDIR="\"/opt/local/etc\"" -I"./darwin" -pipe -Os -arch ppc -MT zfs/ZfsCompressedArcMeter.o -MD -MP -MF $depbase.Tpo -c -o zfs/ZfsCompressedArcMeter.o zfs/ZfsCompressedArcMeter.c &&\
    mv -f $depbase.Tpo $depbase.Po
darwin/DarwinProcess.c: In function ‘DarwinProcess_scanThreads’:
darwin/DarwinProcess.c:427: warning: empty body in an if-statement
darwin/DarwinProcess.c:479: error: ‘thread_extended_info_data_t’ undeclared (first use in this function)
darwin/DarwinProcess.c:479: error: (Each undeclared identifier is reported only once
darwin/DarwinProcess.c:479: error: for each function it appears in.)
darwin/DarwinProcess.c:479: error: expected ‘;’ before ‘extended_info’
darwin/DarwinProcess.c:480: error: ‘THREAD_EXTENDED_INFO_COUNT’ undeclared (first use in this function)
darwin/DarwinProcess.c:481: error: ‘THREAD_EXTENDED_INFO’ undeclared (first use in this function)
darwin/DarwinProcess.c:481: error: ‘extended_info’ undeclared (first use in this function)
make[1]: *** [darwin/DarwinProcess.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_htop/htop/work/htop-3.4.1'
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by BenBE**
Fixes #1686

Untested, but should mimic the old behaviour closely if I didn't mess up anything important …

### CODE REVIEW

**Review by barracuda156 — APPROVED** [review]
Builds fine on 10.6.8 powerpc from the master with this patch applied. Thank you!
